name: Prepare virtual pages index
on: push
permissions:
  contents: write
jobs:
  Prepare-Virtual-Pages-Index:
    # Prevent running action unless it's the original wiki repo
    if: github.repository == 'mgsvmoddingwiki/mgsvmoddingwiki.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Run build script
        run: |
          ./build-virtual-index.ps1
        shell: pwsh
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "CHANGED=false" >>${GITHUB_ENV}
          else
            echo "CHANGED=true" >>${GITHUB_ENV}
          fi
        shell: bash
      - name: Commit changes if they exist
        if: env.CHANGED == 'true'
        env:
          GH_USERNAME: ${{ github.repository_owner }}
          GH_USERID: ${{ github.repository_owner_id }}
        run: |
          git config --global user.email "${GH_USERID}+${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          git add "./assets/js/virtualindex.js"
          git commit -m "Virtual pages index updated"
          git push

